feat: add CI
FideCly/mailer-service pull request #9
Opened 2023-06-21 12:47 UTC by JeremCy

add ci to mailer services

2023-06-21 12:50 UTC, sihamais requested changes

2023-06-21 12:50 UTC, sihamais commented on .github/workflows/node.js.yml
> +        run: npm run test:e2e
C’est des tests unitaires sur ce repo donc ‘npm run test’

2023-06-21 13:36 UTC, sihamais commented on .github/workflows/eslint.yml
Pourquoi t’a enlevé le linter ?

2023-06-21 13:50 UTC, JeremCy commented on .github/workflows/eslint.yml
il fail et cette erreur il me faudra un peut plus de time pour la corriger comme le reste passe je vais le remettre après avoir trouver l'erreur

2023-06-22 08:44 UTC, sihamais commented on .github/workflows/eslint.yml
okk

2023-06-22 08:45 UTC, sihamais approved these changes

2023-06-22 08:45 UTC, merged